### PR TITLE
make pedometer member variable - 103 error fix

### PR DESCRIPTION
**Pull request by antsav**

### CODE REVIEW

**Comment by t0lkman** [comment]
:+1:

**Comment by leecrossley** [comment]
Do you prefer this PR to my [fix of initialising at the start](https://github.com/leecrossley/cordova-plugin-pedometer/commit/a4ecf1dd3527c239f2a9451c35af50b847ac0591#diff-f08fd66e79c3c2700b1164a0b4f380b9R17)? I guess this gives you more control over the "Just In Time" message for the motion permission?

**Comment by antsav** [comment]
for me any approach will work :wink: 
my PR already tested on multiple cases :+1:

**Comment by leecrossley** [comment]
I also tested my fix on Friday but I have merged your PR as I prefer better control over the JIT permission dialog, thanks

**Pull request merged**
